// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class CarouselSliderItemBindings extends WidgetElement {
  CarouselSliderItemBindings(super.context);
  String? get imageUrl;
  set imageUrl(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['image-url'] = ElementAttributeProperty(
      getter: () => imageUrl?.toString(),
      setter: (value) => imageUrl = value,
      deleter: () => imageUrl = null
    );
  }
  static StaticDefinedBindingPropertyMap carouselSliderItemProperties = {
    'imageUrl': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderItemBindings>(element).imageUrl,
      setter: (element, value) =>
      castToType<CarouselSliderItemBindings>(element).imageUrl = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    carouselSliderItemProperties,
  ];
}