// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
enum CarouselSliderScrollDirection {
  horizontal('horizontal'),
  vertical('vertical');
  final String value;
  const CarouselSliderScrollDirection(this.value);
  static CarouselSliderScrollDirection? parse(String? value) {
    if (value == null) return null;
    return CarouselSliderScrollDirection.values.firstWhere(
      (e) => e.value == value,
      orElse: () => throw ArgumentError('Invalid CarouselSliderScrollDirection value: $value'),
    );
  }
  @override
  String toString() => value;
}
abstract class CarouselSliderBindings extends WidgetElement {
  CarouselSliderBindings(super.context);
  double? get height;
  set height(value);
  double? get aspectRatio;
  set aspectRatio(value);
  double? get viewportFraction;
  set viewportFraction(value);
  double? get initialPage;
  set initialPage(value);
  bool get enableInfiniteScroll;
  set enableInfiniteScroll(value);
  bool get animateToClosest;
  set animateToClosest(value);
  bool get reverse;
  set reverse(value);
  bool get autoPlay;
  set autoPlay(value);
  double? get autoPlayInterval;
  set autoPlayInterval(value);
  double? get autoPlayAnimationDuration;
  set autoPlayAnimationDuration(value);
  String? get autoPlayCurve;
  set autoPlayCurve(value);
  bool get enlargeCenterPage;
  set enlargeCenterPage(value);
  dynamic get onPageChanged;
  set onPageChanged(value);
  dynamic get onScrolled;
  set onScrolled(value);
  String? get scrollPhysics;
  set scrollPhysics(value);
  bool get pageSnapping;
  set pageSnapping(value);
  CarouselSliderScrollDirection? get scrollDirection;
  set scrollDirection(value);
  bool get pauseAutoPlayOnTouch;
  set pauseAutoPlayOnTouch(value);
  bool get pauseAutoPlayOnManualNavigate;
  set pauseAutoPlayOnManualNavigate(value);
  bool get pauseAutoPlayInFiniteScroll;
  set pauseAutoPlayInFiniteScroll(value);
  String? get pageViewKey;
  set pageViewKey(value);
  CenterPageEnlargeStrategy? get enlargeStrategy;
  set enlargeStrategy(value);
  double? get enlargeFactor;
  set enlargeFactor(value);
  bool get disableCenter;
  set disableCenter(value);
  bool get padEnds;
  set padEnds(value);
  String? get clipBehavior;
  set clipBehavior(value);
  double? get realPage;
  set realPage(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['height'] = ElementAttributeProperty(
      getter: () => height?.toString(),
      setter: (value) => height = double.tryParse(value) ?? 0.0,
      deleter: () => height = 0.0
    );
    attributes['aspect-ratio'] = ElementAttributeProperty(
      getter: () => aspectRatio?.toString(),
      setter: (value) => aspectRatio = double.tryParse(value) ?? 0.0,
      deleter: () => aspectRatio = 0.0
    );
    attributes['viewport-fraction'] = ElementAttributeProperty(
      getter: () => viewportFraction?.toString(),
      setter: (value) => viewportFraction = double.tryParse(value) ?? 0.0,
      deleter: () => viewportFraction = 0.0
    );
    attributes['initial-page'] = ElementAttributeProperty(
      getter: () => initialPage?.toString(),
      setter: (value) => initialPage = double.tryParse(value) ?? 0.0,
      deleter: () => initialPage = 0.0
    );
    attributes['enable-infinite-scroll'] = ElementAttributeProperty(
      getter: () => enableInfiniteScroll.toString(),
      setter: (value) => enableInfiniteScroll = value == 'true' || value == '',
      deleter: () => enableInfiniteScroll = false
    );
    attributes['animate-to-closest'] = ElementAttributeProperty(
      getter: () => animateToClosest.toString(),
      setter: (value) => animateToClosest = value == 'true' || value == '',
      deleter: () => animateToClosest = false
    );
    attributes['reverse'] = ElementAttributeProperty(
      getter: () => reverse.toString(),
      setter: (value) => reverse = value == 'true' || value == '',
      deleter: () => reverse = false
    );
    attributes['auto-play'] = ElementAttributeProperty(
      getter: () => autoPlay.toString(),
      setter: (value) => autoPlay = value == 'true' || value == '',
      deleter: () => autoPlay = false
    );
    attributes['auto-play-interval'] = ElementAttributeProperty(
      getter: () => autoPlayInterval?.toString(),
      setter: (value) => autoPlayInterval = double.tryParse(value) ?? 0.0,
      deleter: () => autoPlayInterval = 0.0
    );
    attributes['auto-play-animation-duration'] = ElementAttributeProperty(
      getter: () => autoPlayAnimationDuration?.toString(),
      setter: (value) => autoPlayAnimationDuration = double.tryParse(value) ?? 0.0,
      deleter: () => autoPlayAnimationDuration = 0.0
    );
    attributes['auto-play-curve'] = ElementAttributeProperty(
      getter: () => autoPlayCurve?.toString(),
      setter: (value) => autoPlayCurve = value,
      deleter: () => autoPlayCurve = null
    );
    attributes['enlarge-center-page'] = ElementAttributeProperty(
      getter: () => enlargeCenterPage.toString(),
      setter: (value) => enlargeCenterPage = value == 'true' || value == '',
      deleter: () => enlargeCenterPage = false
    );
    attributes['on-page-changed'] = ElementAttributeProperty(
      getter: () => onPageChanged.toString(),
      setter: (value) => onPageChanged = value,
      deleter: () => onPageChanged = null
    );
    attributes['on-scrolled'] = ElementAttributeProperty(
      getter: () => onScrolled.toString(),
      setter: (value) => onScrolled = value,
      deleter: () => onScrolled = null
    );
    attributes['scroll-physics'] = ElementAttributeProperty(
      getter: () => scrollPhysics?.toString(),
      setter: (value) => scrollPhysics = value,
      deleter: () => scrollPhysics = null
    );
    attributes['page-snapping'] = ElementAttributeProperty(
      getter: () => pageSnapping.toString(),
      setter: (value) => pageSnapping = value == 'true' || value == '',
      deleter: () => pageSnapping = false
    );
    attributes['scroll-direction'] = ElementAttributeProperty(
      getter: () => scrollDirection?.value,
      setter: (value) => scrollDirection = CarouselSliderScrollDirection.parse(value),
      deleter: () => scrollDirection = null
    );
    attributes['pause-auto-play-on-touch'] = ElementAttributeProperty(
      getter: () => pauseAutoPlayOnTouch.toString(),
      setter: (value) => pauseAutoPlayOnTouch = value == 'true' || value == '',
      deleter: () => pauseAutoPlayOnTouch = false
    );
    attributes['pause-auto-play-on-manual-navigate'] = ElementAttributeProperty(
      getter: () => pauseAutoPlayOnManualNavigate.toString(),
      setter: (value) => pauseAutoPlayOnManualNavigate = value == 'true' || value == '',
      deleter: () => pauseAutoPlayOnManualNavigate = false
    );
    attributes['pause-auto-play-in-finite-scroll'] = ElementAttributeProperty(
      getter: () => pauseAutoPlayInFiniteScroll.toString(),
      setter: (value) => pauseAutoPlayInFiniteScroll = value == 'true' || value == '',
      deleter: () => pauseAutoPlayInFiniteScroll = false
    );
    attributes['page-view-key'] = ElementAttributeProperty(
      getter: () => pageViewKey?.toString(),
      setter: (value) => pageViewKey = value,
      deleter: () => pageViewKey = null
    );
    attributes['enlarge-strategy'] = ElementAttributeProperty(
      getter: () => enlargeStrategy?.toString(),
      setter: (value) => enlargeStrategy = value,
      deleter: () => enlargeStrategy = null
    );
    attributes['enlarge-factor'] = ElementAttributeProperty(
      getter: () => enlargeFactor?.toString(),
      setter: (value) => enlargeFactor = double.tryParse(value) ?? 0.0,
      deleter: () => enlargeFactor = 0.0
    );
    attributes['disable-center'] = ElementAttributeProperty(
      getter: () => disableCenter.toString(),
      setter: (value) => disableCenter = value == 'true' || value == '',
      deleter: () => disableCenter = false
    );
    attributes['pad-ends'] = ElementAttributeProperty(
      getter: () => padEnds.toString(),
      setter: (value) => padEnds = value == 'true' || value == '',
      deleter: () => padEnds = false
    );
    attributes['clip-behavior'] = ElementAttributeProperty(
      getter: () => clipBehavior?.toString(),
      setter: (value) => clipBehavior = value,
      deleter: () => clipBehavior = null
    );
    attributes['real-page'] = ElementAttributeProperty(
      getter: () => realPage?.toString(),
      setter: (value) => realPage = double.tryParse(value) ?? 0.0,
      deleter: () => realPage = 0.0
    );
  }
  static StaticDefinedBindingPropertyMap carouselSliderProperties = {
    'height': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).height,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).height = value,
    ),
    'aspectRatio': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).aspectRatio,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).aspectRatio = value,
    ),
    'viewportFraction': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).viewportFraction,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).viewportFraction = value,
    ),
    'initialPage': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).initialPage,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).initialPage = value,
    ),
    'enableInfiniteScroll': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).enableInfiniteScroll,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).enableInfiniteScroll = value,
    ),
    'animateToClosest': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).animateToClosest,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).animateToClosest = value,
    ),
    'reverse': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).reverse,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).reverse = value,
    ),
    'autoPlay': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).autoPlay,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).autoPlay = value,
    ),
    'autoPlayInterval': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).autoPlayInterval,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).autoPlayInterval = value,
    ),
    'autoPlayAnimationDuration': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).autoPlayAnimationDuration,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).autoPlayAnimationDuration = value,
    ),
    'autoPlayCurve': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).autoPlayCurve,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).autoPlayCurve = value,
    ),
    'enlargeCenterPage': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).enlargeCenterPage,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).enlargeCenterPage = value,
    ),
    'onPageChanged': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).onPageChanged,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).onPageChanged = value,
    ),
    'onScrolled': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).onScrolled,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).onScrolled = value,
    ),
    'scrollPhysics': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).scrollPhysics,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).scrollPhysics = value,
    ),
    'pageSnapping': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).pageSnapping,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).pageSnapping = value,
    ),
    'scrollDirection': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).scrollDirection,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).scrollDirection = value,
    ),
    'pauseAutoPlayOnTouch': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).pauseAutoPlayOnTouch,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).pauseAutoPlayOnTouch = value,
    ),
    'pauseAutoPlayOnManualNavigate': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).pauseAutoPlayOnManualNavigate,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).pauseAutoPlayOnManualNavigate = value,
    ),
    'pauseAutoPlayInFiniteScroll': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).pauseAutoPlayInFiniteScroll,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).pauseAutoPlayInFiniteScroll = value,
    ),
    'pageViewKey': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).pageViewKey,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).pageViewKey = value,
    ),
    'enlargeStrategy': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).enlargeStrategy,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).enlargeStrategy = value,
    ),
    'enlargeFactor': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).enlargeFactor,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).enlargeFactor = value,
    ),
    'disableCenter': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).disableCenter,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).disableCenter = value,
    ),
    'padEnds': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).padEnds,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).padEnds = value,
    ),
    'clipBehavior': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).clipBehavior,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).clipBehavior = value,
    ),
    'realPage': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).realPage,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).realPage = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    carouselSliderProperties,
  ];
}