// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
import 'package:webf/webf.dart';
abstract class CarouselSliderBindings extends WidgetElement {
  CarouselSliderBindings(super.context);
  bool get autoplay;
  set autoplay(value);
  double? get autoplayDelay;
  set autoplayDelay(value);
  bool get autoplayDisableOnInteraction;
  set autoplayDisableOnInteraction(value);
  double? get speed;
  set speed(value);
  String? get easing;
  set easing(value);
  bool get loop;
  set loop(value);
  String? get direction;
  set direction(value);
  double? get slidesPerView;
  set slidesPerView(value);
  bool get centeredSlides;
  set centeredSlides(value);
  double? get initialSlide;
  set initialSlide(value);
  bool get allowTouchMove;
  set allowTouchMove(value);
  double? get activeIndex;
  set activeIndex(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['autoplay'] = ElementAttributeProperty(
      getter: () => autoplay.toString(),
      setter: (value) => autoplay = value == 'true' || value == '',
      deleter: () => autoplay = false
    );
    attributes['autoplay-delay'] = ElementAttributeProperty(
      getter: () => autoplayDelay?.toString(),
      setter: (value) => autoplayDelay = double.tryParse(value) ?? 0.0,
      deleter: () => autoplayDelay = 0.0
    );
    attributes['autoplay-disable-on-interaction'] = ElementAttributeProperty(
      getter: () => autoplayDisableOnInteraction.toString(),
      setter: (value) => autoplayDisableOnInteraction = value == 'true' || value == '',
      deleter: () => autoplayDisableOnInteraction = false
    );
    attributes['speed'] = ElementAttributeProperty(
      getter: () => speed?.toString(),
      setter: (value) => speed = double.tryParse(value) ?? 0.0,
      deleter: () => speed = 0.0
    );
    attributes['easing'] = ElementAttributeProperty(
      getter: () => easing?.toString(),
      setter: (value) => easing = value,
      deleter: () => easing = null
    );
    attributes['loop'] = ElementAttributeProperty(
      getter: () => loop.toString(),
      setter: (value) => loop = value == 'true' || value == '',
      deleter: () => loop = false
    );
    attributes['direction'] = ElementAttributeProperty(
      getter: () => direction?.toString(),
      setter: (value) => direction = value,
      deleter: () => direction = null
    );
    attributes['slides-per-view'] = ElementAttributeProperty(
      getter: () => slidesPerView?.toString(),
      setter: (value) => slidesPerView = double.tryParse(value) ?? 0.0,
      deleter: () => slidesPerView = 0.0
    );
    attributes['centered-slides'] = ElementAttributeProperty(
      getter: () => centeredSlides.toString(),
      setter: (value) => centeredSlides = value == 'true' || value == '',
      deleter: () => centeredSlides = false
    );
    attributes['initial-slide'] = ElementAttributeProperty(
      getter: () => initialSlide?.toString(),
      setter: (value) => initialSlide = double.tryParse(value) ?? 0.0,
      deleter: () => initialSlide = 0.0
    );
    attributes['allow-touch-move'] = ElementAttributeProperty(
      getter: () => allowTouchMove.toString(),
      setter: (value) => allowTouchMove = value == 'true' || value == '',
      deleter: () => allowTouchMove = false
    );
    attributes['active-index'] = ElementAttributeProperty(
      getter: () => activeIndex?.toString(),
      setter: (value) => activeIndex = double.tryParse(value) ?? 0.0,
      deleter: () => activeIndex = 0.0
    );
  }
  static StaticDefinedBindingPropertyMap carouselSliderProperties = {
    'autoplay': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).autoplay,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).autoplay = value,
    ),
    'autoplayDelay': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).autoplayDelay,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).autoplayDelay = value,
    ),
    'autoplayDisableOnInteraction': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).autoplayDisableOnInteraction,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).autoplayDisableOnInteraction = value,
    ),
    'speed': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).speed,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).speed = value,
    ),
    'easing': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).easing,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).easing = value,
    ),
    'loop': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).loop,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).loop = value,
    ),
    'direction': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).direction,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).direction = value,
    ),
    'slidesPerView': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).slidesPerView,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).slidesPerView = value,
    ),
    'centeredSlides': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).centeredSlides,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).centeredSlides = value,
    ),
    'initialSlide': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).initialSlide,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).initialSlide = value,
    ),
    'allowTouchMove': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).allowTouchMove,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).allowTouchMove = value,
    ),
    'activeIndex': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).activeIndex,
      setter: (element, value) =>
      castToType<CarouselSliderBindings>(element).activeIndex = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
    ...super.properties,
    carouselSliderProperties,
  ];
}