// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf codegen`
// ignore_for_file: avoid_unused_constructor_parameters
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: prefer_void_to_null
// ignore_for_file: strict_top_level_inference
import 'package:webf/webf.dart';

abstract class CarouselSliderBindings extends WidgetElement {
  CarouselSliderBindings(super.context);
  double? get currentIndex;
  set currentIndex(value);
  String? get options;
  set options(value);
  String? get height;
  set height(value);
  double? get aspectRatio;
  set aspectRatio(value);
  double? get viewportFraction;
  set viewportFraction(value);
  double? get initialPage;
  set initialPage(value);
  bool get padEnds;
  set padEnds(value);
  bool get disableCenter;
  set disableCenter(value);
  bool get enableInfiniteScroll;
  set enableInfiniteScroll(value);
  bool get animateToClosest;
  set animateToClosest(value);
  bool get reverse;
  set reverse(value);
  String? get scrollDirection;
  set scrollDirection(value);
  bool get pageSnapping;
  set pageSnapping(value);
  String? get scrollPhysics;
  set scrollPhysics(value);
  bool get autoplay;
  set autoplay(value);
  double? get autoplayInterval;
  set autoplayInterval(value);
  double? get autoPlayAnimationDuration;
  set autoPlayAnimationDuration(value);
  String? get autoPlayCurve;
  set autoPlayCurve(value);
  bool get pauseAutoPlayOnTouch;
  set pauseAutoPlayOnTouch(value);
  bool get pauseAutoPlayOnManualNavigate;
  set pauseAutoPlayOnManualNavigate(value);
  bool get pauseAutoPlayInFiniteScroll;
  set pauseAutoPlayInFiniteScroll(value);
  bool get enlargeCenterPage;
  set enlargeCenterPage(value);
  String? get enlargeStrategy;
  set enlargeStrategy(value);
  double? get enlargeFactor;
  set enlargeFactor(value);
  @override
  void initializeAttributes(Map<String, ElementAttributeProperty> attributes) {
    super.initializeAttributes(attributes);
    attributes['current-index'] = ElementAttributeProperty(
        getter: () => currentIndex?.toString(),
        setter: (value) => currentIndex = double.tryParse(value) ?? 0.0,
        deleter: () => currentIndex = 0.0);
    attributes['options'] = ElementAttributeProperty(
        getter: () => options?.toString(),
        setter: (value) => options = value,
        deleter: () => options = null);
    attributes['height'] = ElementAttributeProperty(
        getter: () => height?.toString(),
        setter: (value) => height = value,
        deleter: () => height = null);
    attributes['aspect-ratio'] = ElementAttributeProperty(
        getter: () => aspectRatio?.toString(),
        setter: (value) => aspectRatio = double.tryParse(value) ?? 0.0,
        deleter: () => aspectRatio = 0.0);
    attributes['viewport-fraction'] = ElementAttributeProperty(
        getter: () => viewportFraction?.toString(),
        setter: (value) => viewportFraction = double.tryParse(value) ?? 0.0,
        deleter: () => viewportFraction = 0.0);
    attributes['initial-page'] = ElementAttributeProperty(
        getter: () => initialPage?.toString(),
        setter: (value) => initialPage = double.tryParse(value) ?? 0.0,
        deleter: () => initialPage = 0.0);
    attributes['pad-ends'] = ElementAttributeProperty(
        getter: () => padEnds.toString(),
        setter: (value) => padEnds = value == 'true' || value == '',
        deleter: () => padEnds = false);
    attributes['disable-center'] = ElementAttributeProperty(
        getter: () => disableCenter.toString(),
        setter: (value) => disableCenter = value == 'true' || value == '',
        deleter: () => disableCenter = false);
    attributes['enable-infinite-scroll'] = ElementAttributeProperty(
        getter: () => enableInfiniteScroll.toString(),
        setter: (value) =>
            enableInfiniteScroll = value == 'true' || value == '',
        deleter: () => enableInfiniteScroll = false);
    attributes['animate-to-closest'] = ElementAttributeProperty(
        getter: () => animateToClosest.toString(),
        setter: (value) => animateToClosest = value == 'true' || value == '',
        deleter: () => animateToClosest = false);
    attributes['reverse'] = ElementAttributeProperty(
        getter: () => reverse.toString(),
        setter: (value) => reverse = value == 'true' || value == '',
        deleter: () => reverse = false);
    attributes['scroll-direction'] = ElementAttributeProperty(
        getter: () => scrollDirection?.toString(),
        setter: (value) => scrollDirection = value,
        deleter: () => scrollDirection = null);
    attributes['page-snapping'] = ElementAttributeProperty(
        getter: () => pageSnapping.toString(),
        setter: (value) => pageSnapping = value == 'true' || value == '',
        deleter: () => pageSnapping = false);
    attributes['scroll-physics'] = ElementAttributeProperty(
        getter: () => scrollPhysics?.toString(),
        setter: (value) => scrollPhysics = value,
        deleter: () => scrollPhysics = null);
    attributes['autoplay'] = ElementAttributeProperty(
        getter: () => autoplay.toString(),
        setter: (value) => autoplay = value == 'true' || value == '',
        deleter: () => autoplay = false);
    attributes['autoplay-interval'] = ElementAttributeProperty(
        getter: () => autoplayInterval?.toString(),
        setter: (value) => autoplayInterval = double.tryParse(value) ?? 0.0,
        deleter: () => autoplayInterval = 0.0);
    attributes['auto-play-animation-duration'] = ElementAttributeProperty(
        getter: () => autoPlayAnimationDuration?.toString(),
        setter: (value) =>
            autoPlayAnimationDuration = double.tryParse(value) ?? 0.0,
        deleter: () => autoPlayAnimationDuration = 0.0);
    attributes['auto-play-curve'] = ElementAttributeProperty(
        getter: () => autoPlayCurve?.toString(),
        setter: (value) => autoPlayCurve = value,
        deleter: () => autoPlayCurve = null);
    attributes['pause-auto-play-on-touch'] = ElementAttributeProperty(
        getter: () => pauseAutoPlayOnTouch.toString(),
        setter: (value) =>
            pauseAutoPlayOnTouch = value == 'true' || value == '',
        deleter: () => pauseAutoPlayOnTouch = false);
    attributes['pause-auto-play-on-manual-navigate'] = ElementAttributeProperty(
        getter: () => pauseAutoPlayOnManualNavigate.toString(),
        setter: (value) =>
            pauseAutoPlayOnManualNavigate = value == 'true' || value == '',
        deleter: () => pauseAutoPlayOnManualNavigate = false);
    attributes['pause-auto-play-in-finite-scroll'] = ElementAttributeProperty(
        getter: () => pauseAutoPlayInFiniteScroll.toString(),
        setter: (value) =>
            pauseAutoPlayInFiniteScroll = value == 'true' || value == '',
        deleter: () => pauseAutoPlayInFiniteScroll = false);
    attributes['enlarge-center-page'] = ElementAttributeProperty(
        getter: () => enlargeCenterPage.toString(),
        setter: (value) => enlargeCenterPage = value == 'true' || value == '',
        deleter: () => enlargeCenterPage = false);
    attributes['enlarge-strategy'] = ElementAttributeProperty(
        getter: () => enlargeStrategy?.toString(),
        setter: (value) => enlargeStrategy = value,
        deleter: () => enlargeStrategy = null);
    attributes['enlarge-factor'] = ElementAttributeProperty(
        getter: () => enlargeFactor?.toString(),
        setter: (value) => enlargeFactor = double.tryParse(value) ?? 0.0,
        deleter: () => enlargeFactor = 0.0);
  }

  static StaticDefinedBindingPropertyMap carouselSliderProperties = {
    'currentIndex': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).currentIndex,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).currentIndex = value,
    ),
    'options': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).options,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).options = value,
    ),
    'height': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).height,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).height = value,
    ),
    'aspectRatio': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).aspectRatio,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).aspectRatio = value,
    ),
    'viewportFraction': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).viewportFraction,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).viewportFraction = value,
    ),
    'initialPage': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).initialPage,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).initialPage = value,
    ),
    'padEnds': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).padEnds,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).padEnds = value,
    ),
    'disableCenter': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).disableCenter,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).disableCenter = value,
    ),
    'enableInfiniteScroll': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).enableInfiniteScroll,
      setter: (element, value) => castToType<CarouselSliderBindings>(element)
          .enableInfiniteScroll = value,
    ),
    'animateToClosest': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).animateToClosest,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).animateToClosest = value,
    ),
    'reverse': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).reverse,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).reverse = value,
    ),
    'scrollDirection': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).scrollDirection,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).scrollDirection = value,
    ),
    'pageSnapping': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).pageSnapping,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).pageSnapping = value,
    ),
    'scrollPhysics': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).scrollPhysics,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).scrollPhysics = value,
    ),
    'autoplay': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element).autoplay,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).autoplay = value,
    ),
    'autoplayInterval': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).autoplayInterval,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).autoplayInterval = value,
    ),
    'autoPlayAnimationDuration': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).autoPlayAnimationDuration,
      setter: (element, value) => castToType<CarouselSliderBindings>(element)
          .autoPlayAnimationDuration = value,
    ),
    'autoPlayCurve': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).autoPlayCurve,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).autoPlayCurve = value,
    ),
    'pauseAutoPlayOnTouch': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).pauseAutoPlayOnTouch,
      setter: (element, value) => castToType<CarouselSliderBindings>(element)
          .pauseAutoPlayOnTouch = value,
    ),
    'pauseAutoPlayOnManualNavigate': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element)
          .pauseAutoPlayOnManualNavigate,
      setter: (element, value) => castToType<CarouselSliderBindings>(element)
          .pauseAutoPlayOnManualNavigate = value,
    ),
    'pauseAutoPlayInFiniteScroll': StaticDefinedBindingProperty(
      getter: (element) => castToType<CarouselSliderBindings>(element)
          .pauseAutoPlayInFiniteScroll,
      setter: (element, value) => castToType<CarouselSliderBindings>(element)
          .pauseAutoPlayInFiniteScroll = value,
    ),
    'enlargeCenterPage': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).enlargeCenterPage,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).enlargeCenterPage = value,
    ),
    'enlargeStrategy': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).enlargeStrategy,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).enlargeStrategy = value,
    ),
    'enlargeFactor': StaticDefinedBindingProperty(
      getter: (element) =>
          castToType<CarouselSliderBindings>(element).enlargeFactor,
      setter: (element, value) =>
          castToType<CarouselSliderBindings>(element).enlargeFactor = value,
    ),
  };
  @override
  List<StaticDefinedBindingPropertyMap> get properties => [
        ...super.properties,
        carouselSliderProperties,
      ];
}
