/* Generated by WebF CLI - aggregated type declarations */
export enum CarouselPageChangedReason { timed = 'timed', manual = 'manual', controller = 'controller' }
export enum CenterPageEnlargeStrategy { scale = 'scale', height = 'height', zoom = 'zoom' }
export enum Axis { horizontal = 'Axis.horizontal', vertical = 'Axis.vertical' }
export enum Curve { ease = 'Curves.ease', easeIn = 'Curves.easeIn', easeOut = 'Curves.easeOut', easeInOut = 'Curves.easeInOut', fastOutSlowIn = 'Curves.fastOutSlowIn', linear = 'Curves.linear' }