/* Generated by WebF CLI - aggregated type declarations */
export type CarouselPageChangedReason = "timed" | "manual" | "controller";
export type CenterPageEnlargeStrategy = "scale" | "height" | "zoom";

export const WEBF_CAROUSEL_TAG = "webf-carousel-slider";
export const WEBF_CAROUSEL_ITEM_TAG = "webf-carousel-slider-item";