/* Generated by WebF CLI - aggregated type declarations */
export type CarouselPageChangedReason = "timed" | "manual" | "controller";
export type CenterPageEnlargeStrategy = "scale" | "height" | "zoom";