/*
 * Generated by TSDL, don't edit this file directly.
 */
// Based on the Vue 3 documentation for defining custom elements:
// https://vuejs.org/guide/extras/web-components
import type { EmitFn, PublicProps, StyleValue, ClassValue } from 'vue';
import '@openwebf/vue-core-ui';
export type CarouselPageChangedReason = "timed" | "manual" | "controller";
export type CenterPageEnlargeStrategy = "scale" | "height" | "zoom";
type EventMap = {
  [event: string]: Event
}
// This maps an EventMap to the format that Vue's $emit type expects.
type VueEmit<T extends EventMap> = EmitFn<{
  [K in keyof T]: (event: NonNullable<T[K]>) => void
}>
// Vue 3 event listener properties for template usage
type VueEventListeners<T extends EventMap> = {
  [K in keyof T as `on${Capitalize<string & K>}`]?: (event: NonNullable<T[K]>) => any
}
type DefineCustomElement<
  ElementType,
  Props,
  Events extends EventMap = {},
> = new () => ElementType & VueEventListeners<Events> & {
  // Use $props to define the properties exposed to template type checking. Vue
  // specifically reads prop definitions from the `$props` type. Note that we
  // combine the element's props with Vue's special props.
  /** @deprecated Do not use the $props property on a Custom Element ref,
    this is for template prop types only. */
  $props: Props & PublicProps & VueEventListeners<Events>
  // Use $emit to specifically define event types. Vue specifically reads event
  // types from the `$emit` type. Note that `$emit` expects a particular format
  // that we map `Events` to.
  /** @deprecated Do not use the $emit property on a Custom Element ref,
    this is for template prop types only. */
  $emit: VueEmit<Events>
}
export type CarouselSliderProps = {
  'height'?: number;
  'aspect-ratio'?: number;
  'viewport-fraction'?: number;
  'initial-page'?: number;
  'enable-infinite-scroll'?: boolean;
  'animate-to-closest'?: boolean;
  'reverse'?: boolean;
  'auto-play'?: boolean;
  'auto-play-interval'?: number;
  'auto-play-animation-duration'?: number;
  'auto-play-curve'?: string;
  'enlarge-center-page'?: boolean;
  'on-page-changed'?: any;
  'on-scrolled'?: any;
  'scroll-physics'?: string;
  'page-snapping'?: boolean;
  'scroll-direction'?: 'horizontal' | 'vertical';
  'pause-auto-play-on-touch'?: boolean;
  'pause-auto-play-on-manual-navigate'?: boolean;
  'pause-auto-play-in-finite-scroll'?: boolean;
  'page-view-key'?: string;
  'enlarge-strategy'?: 'scale' | 'height' | 'zoom';
  'enlarge-factor'?: number;
  'disable-center'?: boolean;
  'pad-ends'?: boolean;
  'clip-behavior'?: string;
  'disable-gesture'?: boolean;
  'real-page'?: number;
  'id'?: string;
  'class'?: ClassValue;
  'style'?: StyleValue;
}
export interface CarouselSliderElement {
  height?: number;
  aspectRatio?: number;
  viewportFraction?: number;
  initialPage?: number;
  enableInfiniteScroll?: boolean;
  animateToClosest?: boolean;
  reverse?: boolean;
  autoPlay?: boolean;
  autoPlayInterval?: number;
  autoPlayAnimationDuration?: number;
  autoPlayCurve?: string;
  enlargeCenterPage?: boolean;
  onPageChanged?: any;
  onScrolled?: any;
  scrollPhysics?: string;
  pageSnapping?: boolean;
  scrollDirection?: 'horizontal' | 'vertical';
  pauseAutoPlayOnTouch?: boolean;
  pauseAutoPlayOnManualNavigate?: boolean;
  pauseAutoPlayInFiniteScroll?: boolean;
  pageViewKey?: string;
  enlargeStrategy?: 'scale' | 'height' | 'zoom';
  enlargeFactor?: number;
  disableCenter?: boolean;
  padEnds?: boolean;
  clipBehavior?: string;
  disableGesture?: boolean;
  realPage?: number;
  nextPage(duration: number, curve: string): void;
  previousPage(duration: number, curve: string): void;
  jumpToPage(page: number): void;
  animateToPage(page: number, duration: number, curve: string): void;
  startAutoPlay(): void;
  stopAutoPlay(): void;
}
export type CarouselSliderEvents = {
}
export type CarouselSliderItemProps = {
  'image-url'?: string;
  'id'?: string;
  'class'?: ClassValue;
  'style'?: StyleValue;
}
export interface CarouselSliderItemElement {
  imageUrl?: string;
}
export type CarouselSliderItemEvents = {
}
declare const flutterAttached: (typeof import('@openwebf/vue-core-ui')) extends { flutterAttached: infer T } ? T : any;
declare module '@vue/runtime-core' {
  interface GlobalDirectives {
    vFlutterAttached: typeof flutterAttached;
  }
  interface GlobalComponents {
    'carousel-slider': DefineCustomElement<
      CarouselSliderElement,
      CarouselSliderProps,
      CarouselSliderEvents
    >
    'carousel-slider-item': DefineCustomElement<
      CarouselSliderItemElement,
      CarouselSliderItemProps,
      CarouselSliderItemEvents
    >
  }
}
// Some tooling (older IDE integrations) look for global directive/component typing
// augmentations on the `vue` module name instead of `@vue/runtime-core`.
declare module 'vue' {
  interface GlobalDirectives extends import('@vue/runtime-core').GlobalDirectives {}
  interface GlobalComponents extends import('@vue/runtime-core').GlobalComponents {}
}