/*
 * Generated by TSDL, don't edit this file directly.
 */
// Based on the Vue 3 documentation for defining custom elements:
// https://vuejs.org/guide/extras/web-components
import type { EmitFn, PublicProps, StyleValue, ClassValue } from 'vue';
import '@openwebf/vue-core-ui';
export type CarouselChangeReason = "autoplay" | "drag" | "api";
type EventMap = {
  [event: string]: Event
}
// This maps an EventMap to the format that Vue's $emit type expects.
type VueEmit<T extends EventMap> = EmitFn<{
  [K in keyof T]: (event: NonNullable<T[K]>) => void
}>
// Vue 3 event listener properties for template usage
type VueEventListeners<T extends EventMap> = {
  [K in keyof T as `on${Capitalize<string & K>}`]?: (event: NonNullable<T[K]>) => any
}
type DefineCustomElement<
  ElementType,
  Props,
  Events extends EventMap = {},
> = new () => ElementType & VueEventListeners<Events> & {
  // Use $props to define the properties exposed to template type checking. Vue
  // specifically reads prop definitions from the `$props` type. Note that we
  // combine the element's props with Vue's special props.
  /** @deprecated Do not use the $props property on a Custom Element ref,
    this is for template prop types only. */
  $props: Props & PublicProps & VueEventListeners<Events>
  // Use $emit to specifically define event types. Vue specifically reads event
  // types from the `$emit` type. Note that `$emit` expects a particular format
  // that we map `Events` to.
  /** @deprecated Do not use the $emit property on a Custom Element ref,
    this is for template prop types only. */
  $emit: VueEmit<Events>
}
export type CarouselSliderProps = {
  'autoplay'?: boolean;
  'autoplay-delay'?: number;
  'autoplay-disable-on-interaction'?: boolean;
  'speed'?: number;
  'easing'?: string;
  'loop'?: boolean;
  'direction'?: string;
  'slides-per-view'?: number;
  'centered-slides'?: boolean;
  'initial-slide'?: number;
  'allow-touch-move'?: boolean;
  'active-index'?: number;
  'id'?: string;
  'class'?: ClassValue;
  'style'?: StyleValue;
}
export interface CarouselSliderElement {
  autoplay?: boolean;
  autoplayDelay?: number;
  autoplayDisableOnInteraction?: boolean;
  speed?: number;
  easing?: string;
  loop?: boolean;
  direction?: string;
  slidesPerView?: number;
  centeredSlides?: boolean;
  initialSlide?: number;
  allowTouchMove?: boolean;
  activeIndex?: number;
  slideNext(speed: number): void;
  slidePrev(speed: number): void;
  slideTo(index: number, speed: number): void;
  autoplayStart(): void;
  autoplayStop(): void;
}
export type CarouselSliderEvents = {
  change: CustomEvent<{ index: number; previousIndex: number; reason: CarouselChangeReason }>;
  changestart: CustomEvent<{ index: number }>;
  changeend: CustomEvent<{ index: number }>;
  play: Event;
  pause: Event;
}
export type CarouselSliderItemProps = {
  'image-url'?: string;
  'id'?: string;
  'class'?: ClassValue;
  'style'?: StyleValue;
}
export interface CarouselSliderItemElement {
  imageUrl?: string;
}
export type CarouselSliderItemEvents = {
}
declare const flutterAttached: (typeof import('@openwebf/vue-core-ui')) extends { flutterAttached: infer T } ? T : any;
declare module '@vue/runtime-core' {
  interface GlobalDirectives {
    vFlutterAttached: typeof flutterAttached;
  }
  interface GlobalComponents {
    'carousel-slider': DefineCustomElement<
      CarouselSliderElement,
      CarouselSliderProps,
      CarouselSliderEvents
    >
    'carousel-slider-item': DefineCustomElement<
      CarouselSliderItemElement,
      CarouselSliderItemProps,
      CarouselSliderItemEvents
    >
  }
}
// Some tooling (older IDE integrations) look for global directive/component typing
// augmentations on the `vue` module name instead of `@vue/runtime-core`.
declare module 'vue' {
  interface GlobalDirectives extends import('@vue/runtime-core').GlobalDirectives {}
  interface GlobalComponents extends import('@vue/runtime-core').GlobalComponents {}
}